# Generated by Django 4.0.1 on 2022-03-01 21:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('email', models.CharField(max_length=122)),
                ('prefftime', models.TimeField()),
                ('contact', models.TimeField()),
                ('bit', models.CharField(max_length=10)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime(2022, 3, 2, 2, 38, 0, 304295))),
            ],
        ),
    ]
