# Generated by Django 4.0.1 on 2022-03-01 21:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdata',
            name='contact',
            field=models.CharField(max_length=122),
        ),
        migrations.AlterField(
            model_name='customerdata',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 3, 2, 2, 46, 52, 941425)),
        ),
    ]
