# Generated by Django 4.0.1 on 2022-03-08 21:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_alter_customerdata_contact_alter_customerdata_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerdata',
            name='bit',
        ),
        migrations.RemoveField(
            model_name='customerdata',
            name='prefftime',
        ),
        migrations.AddField(
            model_name='customerdata',
            name='password',
            field=models.CharField(default='thakgayavro', max_length=122),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customerdata',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 3, 9, 2, 55, 10, 203471)),
        ),
    ]
