# Generated by Django 4.0.1 on 2022-03-08 23:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_remove_customerdata_bit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueryList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefftime1', models.TimeField()),
                ('prefftime2', models.TimeField()),
                ('prefftime3', models.TimeField()),
                ('bit', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='customerdata',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 3, 9, 4, 48, 51, 690358)),
        ),
    ]
