# Generated by Django 4.0.1 on 2022-03-01 14:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShopData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('phone', models.CharField(max_length=122)),
                ('email', models.CharField(max_length=122)),
                ('Opentime', models.DateTimeField()),
                ('closetime', models.DateTimeField()),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime(2022, 3, 1, 19, 42, 11, 488760))),
            ],
        ),
    ]
