# Generated by Django 4.0.1 on 2022-03-01 21:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopkeeper', '0003_alter_shopdata_opentime_alter_shopdata_closetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopdata',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 3, 2, 2, 38, 0, 418705)),
        ),
    ]
